services:
  db:
    image: mysql:latest
    container_name: mysql-app
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=superSecretPassword
      - MYSQL_DATABASE=ventas
    volumes:
      - ./db-docker:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-app
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: superSecretPassword
    ports:
      - "8080:80"
